# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4983a96f13be3fe13cbd76b79e2659012f96b35f90d253ab52cfd0f632aff9117f41cf50720f454065dfe5d5d625e29f8fa89b0b92c7a675128297c755dfb8

test:
  secret_key_base: 0c9a222dd6e7da39f410fe31326b5fbd27297dc353d1ef1faf48cd7ce4b871ceae74e64a260fb596315509e781cc1bc98c30c6712d295d5e78c6206fe23ffb80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
